/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-12 02:00:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/ezen/Desktop/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OTTT1/WEB-INF/lib/spring-webmvc-5.2.23.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1679289164000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1679282840646L));
    _jspx_dependants.put("jar:file:/C:/Users/ezen/Desktop/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OTTT1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.23.RELEASE.jar", Long.valueOf(1679362826855L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLDecoder");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/login/register.css\" >\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("    	.ott-logo-img:hover,\r\n");
      out.write("		.ott-logo-img.active {\r\n");
      out.write("			outline: 3px solid #33ff33;\r\n");
      out.write("		}\r\n");
      out.write("    </style>\r\n");
      out.write("    <title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #202020;\">\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<div class=\"logo\">\r\n");
      out.write("				 <a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo/OTTT.png\" alt=\"로고\">\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"gnb\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">영화</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">드라마</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\">예능</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">애니</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\">게시판</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"h-icon\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("                <!-- <img src=\"./images/icon/search02.png\" alt=\"검색\"> -->\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write(" \" class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginout}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                <!-- <img src=\"./images/icon/user01.png\" alt=\"내 정보\"> -->\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        	</div>\r\n");
      out.write("		</header>\r\n");
      out.write("        \r\n");
      out.write("		<section class=\"sec00\">\r\n");
      out.write("		    ");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/login/register.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/login/register.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/login/register.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/login/register.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("loginout");
      // /WEB-INF/views/login/register.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/login/register.jsp(7,0) '${sessionScope.id == null ? 'logout' : 'login'}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.id == null ? 'logout' : 'login'}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/login/register.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("loginoutlink");
      // /WEB-INF/views/login/register.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/login/register.jsp(8,0) '${sessionScope.id==null ? '/login' : '/mypage'}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.id==null ? '/login' : '/mypage'}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/login/register.jsp(29,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/login/register.jsp(36,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/genre/movie");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/login/register.jsp(39,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/genre/drama");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/login/register.jsp(42,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/genre/interest");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/views/login/register.jsp(45,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/genre/animation");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/views/login/register.jsp(48,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/community");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/views/login/register.jsp(55,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/search");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/views/login/register.jsp(60,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginoutlink}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/views/login/register.jsp(69,6) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setModelAttribute("userDTO");
      // /WEB-INF/views/login/register.jsp(69,6) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("post");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		    <h1 style=\"font-size: 21px; display: inline-block;\">회원가입</h1>\r\n");
            out.write("		    	<div>\r\n");
            out.write("					<div class=\"Id\">\r\n");
            out.write("							<input type=\"text\" name=\"user_id\" class=\"id_input\" id=\"id\" title=\"ID\" maxlength=\"15\"  placeholder=\"아이디 입력\" required pattern=\"^[a-zA-Z0-9]+$\">\r\n");
            out.write("					    <span class=\"errorMsg\" id=\"idErrorMsg\" style=\"position: absolute; left: 910px;\"></span> \r\n");
            out.write("					    <div class=\"idChk\">\r\n");
            out.write("					    	<span class=\"id_input_re_1\">사용 가능한 아이디입니다.</span>\r\n");
            out.write("							<span class=\"id_input_re_2\">아이디가 이미 존재합니다.</span>\r\n");
            out.write("					    </div>\r\n");
            out.write("					  \r\n");
            out.write("					</div>\r\n");
            out.write("					\r\n");
            out.write("					<div class=\"password\">\r\n");
            out.write("					    <input type=\"password\" name=\"user_pwd\" id=\"password\" title=\"PW\" maxlength=\"20\" placeholder=\"비밀번호 입력\" required pattern=\"^(?=.*\\d)(?=.*[a-z])(?=.*[^\\da-zA-Z])(.{8,20})$\">\r\n");
            out.write("					    <span class=\"errorMsg\" id=\"passwordErrorMsg\"></span>\r\n");
            out.write("					</div>\r\n");
            out.write("					\r\n");
            out.write("					<div class=\"passwordCheck\">\r\n");
            out.write("					    <input type=\"password\" id=\"passwordCheck\" title=\"PWC\" maxlength=\"20\" placeholder=\"비밀번호 재확인\" required>\r\n");
            out.write("					    <span class=\"errorMsg\" id=\"passwordCheckErrorMsg\"></span>\r\n");
            out.write("					</div>\r\n");
            out.write("				</div>\r\n");
            out.write("				\r\n");
            out.write("				<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
            out.write("				\r\n");
            out.write("				<script>\r\n");
            out.write("		    	//아이디 중복검사\r\n");
            out.write("				$('.id_input').on(\"propertychange change keyup paste input\", function(){\r\n");
            out.write("					\r\n");
            out.write("					var user_id = $('.id_input').val();			// .id_input에 입력되는 값\r\n");
            out.write("				  	var data = {user_id : user_id};				// '컨트롤에 넘길 데이터 이름' : '데이터(.id_input에 입력되는 값)'\r\n");
            out.write("				  \r\n");
            out.write("				  	$.ajax({\r\n");
            out.write("				  		type : \"post\",\r\n");
            out.write("					    url : \"/ottt/signin/memberIdChk\",\r\n");
            out.write("					    data : data,\r\n");
            out.write("					    success : function(result){\r\n");
            out.write("					    	\r\n");
            out.write("					    	//console.log(\"성공 여부\" + result);					    	\r\n");
            out.write("							if(result != 'success'){\r\n");
            out.write("								$('.id_input_re_1').css(\"display\",\"inline-block\");\r\n");
            out.write("								$('.id_input_re_2').css(\"display\", \"none\");\r\n");
            out.write("							} else {\r\n");
            out.write("								$('.id_input_re_2').css(\"display\",\"inline-block\");\r\n");
            out.write("								$('.id_input_re_1').css(\"display\", \"none\");	\r\n");
            out.write("							}\r\n");
            out.write("				     \r\n");
            out.write("						}// success 종료\r\n");
            out.write("				\r\n");
            out.write("					}); // ajax 종료\r\n");
            out.write("				\r\n");
            out.write("				});// function 종료\r\n");
            out.write("				\r\n");
            out.write("				$(document).ready(function() {\r\n");
            out.write("					\r\n");
            out.write("					// 아이디 유효성 검사\r\n");
            out.write("			        $('#id').on('blur', function() {\r\n");
            out.write("			        	\r\n");
            out.write("			        	var idValue = $(this).val();\r\n");
            out.write("			          	var idRegex = /^[a-zA-Z0-9]+$/;\r\n");
            out.write("			          	\r\n");
            out.write("			          	if (!idRegex.test(idValue)) {\r\n");
            out.write("			          		$('#idErrorMsg').text('아이디는 영문자와 숫자만 사용 가능합니다.');\r\n");
            out.write("			          	} else if (idValue.length < 6) {\r\n");
            out.write("			          		$('#idErrorMsg').text('아이디는 6자 이상이어야 합니다.');\r\n");
            out.write("			          	} else {\r\n");
            out.write("			          		$('#idErrorMsg').text('');\r\n");
            out.write("		          		}\r\n");
            out.write("		          	});\r\n");
            out.write("		        \r\n");
            out.write("					// 비밀번호 유효성 검사\r\n");
            out.write("					$('#password').on('blur', function() {\r\n");
            out.write("						\r\n");
            out.write("						var passwordValue = $(this).val();\r\n");
            out.write("					  	var passwordRegex = /^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{8,}$/;\r\n");
            out.write("					  	\r\n");
            out.write("					  	if (!passwordRegex.test(passwordValue)) {\r\n");
            out.write("					  		$('#passwordErrorMsg').text('영문, 숫자, 특수문자를 포함하여 최소8자리 이상으로 입력해야 합니다.');\r\n");
            out.write("					  	} else {\r\n");
            out.write("					  		$('#passwordErrorMsg').text('');\r\n");
            out.write("				  		}\r\n");
            out.write("				  	});\r\n");
            out.write("		        \r\n");
            out.write("			        // 비밀번호 재확인\r\n");
            out.write("			        $('#passwordCheck').on('blur', function() {\r\n");
            out.write("			        	\r\n");
            out.write("			        	var passwordValue = $('#password').val();\r\n");
            out.write("			        	var passwordCheckValue = $(this).val();\r\n");
            out.write("			        	\r\n");
            out.write("			        	if (passwordValue !== passwordCheckValue) {\r\n");
            out.write("			        		$('#passwordCheckErrorMsg').text('비밀번호가 일치하지 않습니다.');\r\n");
            out.write("		        		} else {\r\n");
            out.write("		        			$('#passwordCheckErrorMsg').text('');\r\n");
            out.write("	        			}\r\n");
            out.write("		        	});\r\n");
            out.write("		        	\r\n");
            out.write("			        //이름 유효성검사\r\n");
            out.write("			        $(\"#name\").on(\"blur\",function(){\r\n");
            out.write("			        	\r\n");
            out.write("			        	var nameRegex = /^[가-힣]{2,4}$/;\r\n");
            out.write("		            	var nameValue = $(this).val();\r\n");
            out.write("		            	\r\n");
            out.write("		            	if(!nameRegex.test(nameValue)){\r\n");
            out.write("		            		$('#nameErrorMsg').text('한글만 입력 가능합니다.');\r\n");
            out.write("	            		} else{\r\n");
            out.write("	            			$('#nameErrorMsg').text('');\r\n");
            out.write("            			}\r\n");
            out.write("	            	});\r\n");
            out.write("		        });\r\n");
            out.write("		        </script>\r\n");
            out.write("		        \r\n");
            out.write("		        <div class=\"name\">\r\n");
            out.write("		        	<input type=\"text\" name=\"user_nm\" id=\"name\" title=\"NM\" maxlength=\"10\" placeholder=\"이름\" >\r\n");
            out.write("		        	<span>\r\n");
            out.write("		        		<select name=\"user_gen\">\r\n");
            out.write("				            <option value=\"\">선택</option>\r\n");
            out.write("				            <option value=\"1\">남자</option>\r\n");
            out.write("				            <option value=\"2\">여자</option>\r\n");
            out.write("				            <option value=\"0\">비공개</option>\r\n");
            out.write("			            </select>\r\n");
            out.write("		            </span>\r\n");
            out.write("		            \r\n");
            out.write("		            <script>\r\n");
            out.write("			            const form = document.querySelector('form');\r\n");
            out.write("			            const genderSelect = form.querySelector('select[name=\"user_gen\"]');\r\n");
            out.write("			\r\n");
            out.write("			            form.addEventListener('submit', (event) => {\r\n");
            out.write("			            	if (genderSelect.value === '') {\r\n");
            out.write("			            		event.preventDefault(); // 폼 제출을 막습니다.\r\n");
            out.write("			                	alert('성별을 선택해주세요.');\r\n");
            out.write("		            		}\r\n");
            out.write("		            	});\r\n");
            out.write("					</script>\r\n");
            out.write("		\r\n");
            out.write("					<div class=\"nname\">\r\n");
            out.write("						<input type=\"text\" name=\"user_nicknm\" class=\"nnmame_input\" id=\"nname\" title=\"NNM\" maxlength=\"10\" placeholder=\"닉네임\" >\r\n");
            out.write("						\r\n");
            out.write("						<div class=\"nicknameChk\">\r\n");
            out.write("							<span class=\"errorMsg\" id=\"nnameErrorMsg\" style=\"position: absolute; left: 910px;\"></span>\r\n");
            out.write("					    	<span class=\"nickname_input_re_1\">사용 가능한 닉네임입니다.</span>\r\n");
            out.write("							<span class=\"nickname_input_re_2\">닉네임이 이미 존재합니다.</span>\r\n");
            out.write("					    </div>\r\n");
            out.write("					</div>\r\n");
            out.write("					\r\n");
            out.write("					<script>\r\n");
            out.write("		    	//닉네임 중복검사\r\n");
            out.write("				$('.nnmame_input').on(\"propertychange change keyup paste input\", function(){\r\n");
            out.write("					\r\n");
            out.write("					var user_nicknm = $('.nnmame_input').val();			// .id_input에 입력되는 값\r\n");
            out.write("				  	var data = {user_nicknm : user_nicknm};				// '컨트롤에 넘길 데이터 이름' : '데이터(.id_input에 입력되는 값)'\r\n");
            out.write("				  \r\n");
            out.write("				  	$.ajax({\r\n");
            out.write("				  		type : \"post\",\r\n");
            out.write("					    url : \"/ottt/signin/nnameIdChk\",\r\n");
            out.write("					    data : data,\r\n");
            out.write("					    success : function(result){\r\n");
            out.write("					    	\r\n");
            out.write("					    	//console.log(\"성공 여부\" + result);					    	\r\n");
            out.write("							if(result != 'success'){\r\n");
            out.write("								$('.nickname_input_re_1').css(\"display\",\"inline-block\");\r\n");
            out.write("								$('.nickname_input_re_2').css(\"display\", \"none\");\r\n");
            out.write("							} else {\r\n");
            out.write("								$('.nickname_input_re_2').css(\"display\",\"inline-block\");\r\n");
            out.write("								$('.nickname_input_re_1').css(\"display\", \"none\");	\r\n");
            out.write("							}\r\n");
            out.write("				     \r\n");
            out.write("						}// success 종료\r\n");
            out.write("				\r\n");
            out.write("					}); // ajax 종료\r\n");
            out.write("				\r\n");
            out.write("				});// function 종료\r\n");
            out.write("				\r\n");
            out.write("			        //닉네임 유효성검사\r\n");
            out.write("			        $(\"#nname\").on(\"blur\",function(){\r\n");
            out.write("					    var nnameRegex = /^[가-힣a-zA-Z0-9]{1,8}$/;\r\n");
            out.write("					    var nnameValue = $(this).val();\r\n");
            out.write("					    \r\n");
            out.write("					    if(!nameRegex.test(nameValue)){\r\n");
            out.write("					        $('#nnameErrorMsg').text('1글자 이상 8글자 이하의 한글, 영문, 숫자만 사용 가능합니다.');\r\n");
            out.write("					    } else{\r\n");
            out.write("					        $('#nnameErrorMsg').text('');\r\n");
            out.write("					    }\r\n");
            out.write("					});\r\n");
            out.write("		\r\n");
            out.write("		     \r\n");
            out.write("		        $(document).ready(function(){\r\n");
            out.write("		        	\r\n");
            out.write("		        	$(\".join_button\").click(function(){\r\n");
            out.write("		        		//회원가입 버튼(회원가입 기능 작동)\r\n");
            out.write("		        		if(idRegex&&idValue&&passwordValue&&passwordCheckValue&&passwordRegex&&nameValue&&nameRegex&&nnameRegex&&nnameValue&&emailInput){\r\n");
            out.write("		        			$(\"#membership\").attr(\"action\", \"/member/join\");\r\n");
            out.write("		        			$(\"#membership\").submit();\r\n");
            out.write("	        			}\r\n");
            out.write("		        		\r\n");
            out.write("		        		return false;\r\n");
            out.write("	        		});\r\n");
            out.write("	        	});\r\n");
            out.write("		        \r\n");
            out.write("		        </script>\r\n");
            out.write("					\r\n");
            out.write("					\r\n");
            out.write("					<script>\r\n");
            out.write("			            const form2 = document.querySelector('form2');\r\n");
            out.write("			            const emailInput = document.querySelector('#email');\r\n");
            out.write("			            \r\n");
            out.write("			            function validateEmail(email) {\r\n");
            out.write("			            	const re = /\\S+@\\S+\\.\\S+/;\r\n");
            out.write("			            	return re.test(email);\r\n");
            out.write("		            	}\r\n");
            out.write("			            \r\n");
            out.write("			            form.addEventListener('submit', function(event) {\r\n");
            out.write("			            	const email = emailInput.value.trim();\r\n");
            out.write("			            	if (!validateEmail(email)) {\r\n");
            out.write("			            		alert('유효한 이메일 주소를 입력해주세요.');\r\n");
            out.write("			            		event.preventDefault();\r\n");
            out.write("		            		}\r\n");
            out.write("		            	});\r\n");
            out.write("		            </script>\r\n");
            out.write("		\r\n");
            out.write("		          	<div class=\"email\">\r\n");
            out.write("		           		<input type=\"email\" name=\"user_email\" id=\"email\" title=\"EM\" maxlength=\"20\"  placeholder=\"이메일\" >\r\n");
            out.write("		           		<span>\r\n");
            out.write("		            		<select id=\"domain\" name=\"직접입력\">\r\n");
            out.write("								<option value=\"select\">직접입력</option>\r\n");
            out.write("								<option value=\"naver.com\">네이버</option>\r\n");
            out.write("								<option value=\"gmail.com\">구글</option>\r\n");
            out.write("							</select>\r\n");
            out.write("						</span>\r\n");
            out.write("					\r\n");
            out.write("			           	<script>\r\n");
            out.write("			           		document.getElementById('domain').addEventListener('change', function() {\r\n");
            out.write("			           			var domain = this.value;\r\n");
            out.write("			           			if (domain !== 'select') {\r\n");
            out.write("			           				document.getElementById('email').value += '@' + domain;\r\n");
            out.write("	           					}\r\n");
            out.write("		           			});\r\n");
            out.write("		           		</script>\r\n");
            out.write("		           		\r\n");
            out.write("		           		<button id=\"send-verification-code\">인증번호 발송</button>\r\n");
            out.write("           			</div>\r\n");
            out.write("           			\r\n");
            out.write("		          	<div class=\"Certification\">\r\n");
            out.write("		          		<input type=\"text\" id=\"Certification\" title=\"EM\" maxlength=\"20\"  placeholder=\"인증번호\" >\r\n");
            out.write("			          	<button disabled id=\"completion\" onclick=\"checkCompletion()\">인증확인</button>\r\n");
            out.write("		          	</div>\r\n");
            out.write("		          	\r\n");
            out.write("		          	<div class=\"back\">\r\n");
            out.write("		          		<input type=\"button\" value=\"이전\" onClick=\"location.href='");
            if (_jspx_meth_c_005furl_005f8(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("'\">\r\n");
            out.write("	          		</div>\r\n");
            out.write("	          		\r\n");
            out.write("	          		<div class=\"complate\">\r\n");
            out.write("	          			<input type=\"submit\" value=\"회원가입\">\r\n");
            out.write("          			</div>\r\n");
            out.write("       			</div>\r\n");
            out.write("   			");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/views/login/register.jsp(317,70) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/login");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }
}
